FROM docker.io/library/archlinux:latest
LABEL maintainer "djds <djds@bghost.xyz>"

RUN pacman-key --init \
    && pacman -Syu --noconfirm \
    && pacman -S --noconfirm \
        chromium \
        noto-fonts \
        noto-fonts-cjk \
        noto-fonts-emoji \
        mesa \
        vulkan-intel \
        vulkan-mesa-layers \
        libva-mesa-driver \
        wayland \
    && pacman -Scc --noconfirm

ARG GID
ARG PLUGDEV
ARG UID
ARG AUDIO
ARG USERNAME="chromium"

RUN groupadd -g "${GID}" "${USERNAME}" \
    && groupadd -g "${PLUGDEV}" plugdev \
    && groupmod -g "${AUDIO}" audio \
    && useradd -m -G audio,video,plugdev -u "${UID}" -g "${GID}" "${USERNAME}" \
    && install -m 0700 -d "/home/${USERNAME}/Downloads" \
    && install -m 0700 -d "/home/${USERNAME}/.config/chromium" \
    && chown -R "${USERNAME}:${USERNAME}" "/home/${USERNAME}"

VOLUME ["/home/${USERNAME}/Downloads", "/home/${USERNAME}/.config/chromium"]

WORKDIR "/home/${USERNAME}"

# Run as non privileged user
USER "${USERNAME}"

ENTRYPOINT ["/usr/bin/chromium"]

# vim:ft=dockerfile
