FROM docker.io/library/archlinux:latest
LABEL maintainer "djds djds@bghost.xyz"

RUN set -e \
    ; pacman-key --init \
    && pacman -Syu --noconfirm \
    && pacman -S --noconfirm \
        chromium \
        libva-mesa-driver \
        libfido2 \
        mesa \
        noto-fonts \
        noto-fonts-cjk \
        noto-fonts-emoji \
        vulkan-intel \
    && pacman -Scc --noconfirm

ARG GID
ARG PLUGDEV
ARG ID
ARG AUDIO
ARG USERNAME="chromium"

RUN set -e \
    ; groupadd -g "${GID}" "${USERNAME}" \
    && groupadd -g "${PLUGDEV}" plugdev \
    && groupmod -g "${AUDIO}" audio \
    && useradd -m -G audio,video,plugdev -u "${ID}" -g "${GID}" "${USERNAME}" \
    && install -m 0700 -d "/home/${USERNAME}/Downloads" \
    && chown -R "${USERNAME}:${USERNAME}" "/home/${USERNAME}"

VOLUME ["/home/${USERNAME}/Downloads"]

WORKDIR "/home/${USERNAME}"

# Run as non privileged user
USER "${USERNAME}"

ENTRYPOINT ["/usr/bin/chromium"]

# vim:ft=dockerfile
